
'use client'
import { NextUIProvider } from '@nextui-org/react';
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './utils/provider';
import UsernameContext from './context/userNameContext';
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useState } from 'react';
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: 1,
      staleTime: Infinity,
    },
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [userName, setUserName] = useState<string>("You")
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <QueryClientProvider client={queryClient}>
            <UsernameContext.Provider value={{userName, setUserName}}>
            {children} 
            </UsernameContext.Provider>
          </QueryClientProvider>
        </NextUIProvider>
      </body>
    </html>
  )
}






// no need of this 

// now it will work as nextui prvider  wrapped properly
